### ISSUE TITLE
Translation not happening

### ISSUE THREAD

**Issue by chrisjacobs91** [symdesign/sketch-auto-translate#2]
- I have entered google API key
- I select a text layer
- I select 'Translate selection'
- Nothing happens (no error messages)

Sketch version 51.2

**Comment by symdesign** [comment]
Oh, this is strange. You could track errors through the command line tool [`skpm`](https://github.com/skpm/skpm) and post it here.

**Comment by symdesign** [comment]
@chrisjacobs91 Please note that only text which is located on an artboard will be translated. Let me know if it worked.
